import PDFDocument from 'pdfkit';

interface MagnetData {
  title: string;
  raw_markdown_content: string;
  creators: {
    channel_name: string;
    display_name?: string;
  };
  pdf_footer_text?: string;
  include_cta_page?: boolean;
  cta_page_heading?: string;
  cta_page_body?: string;
  cta_page_url?: string;
  accent_color?: string;
}

export async function generatePDF(magnet: MagnetData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margin: 60,
      size: 'letter',
      bufferPages: true,
      info: {
        Title: magnet.title,
        Author: magnet.creators.display_name || magnet.creators.channel_name,
        Creator: 'MagnetVault',
      },
    });

    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const accentColor = magnet.accent_color || '#4F46E5';
    const textColor = '#1E293B';
    const mutedColor = '#64748B';

    // ---- TITLE PAGE ----
    doc.moveDown(6);
    doc.fillColor(accentColor)
      .font('Helvetica-Bold')
      .fontSize(28)
      .text(magnet.title, { align: 'center' });

    doc.moveDown(1);
    doc.fillColor(mutedColor)
      .font('Helvetica')
      .fontSize(12)
      .text(
        `by ${magnet.creators.display_name || magnet.creators.channel_name}`,
        { align: 'center' }
      );

    doc.moveDown(2);
    doc.strokeColor('#E2E8F0')
      .lineWidth(1)
      .moveTo(doc.page.margins.left, doc.y)
      .lineTo(doc.page.width - doc.page.margins.right, doc.y)
      .stroke();

    // ---- CONTENT PAGES ----
    doc.addPage();
    renderMarkdownToPDF(doc, magnet.raw_markdown_content, {
      textColor,
      accentColor,
      mutedColor,
    });

    // ---- CTA PAGE (optional) ----
    if (magnet.include_cta_page && magnet.cta_page_heading) {
      doc.addPage();
      doc.moveDown(4);
      doc.fillColor(accentColor)
        .font('Helvetica-Bold')
        .fontSize(22)
        .text(magnet.cta_page_heading, { align: 'center' });

      if (magnet.cta_page_body) {
        doc.moveDown(1);
        doc.fillColor(textColor)
          .font('Helvetica')
          .fontSize(12)
          .text(magnet.cta_page_body, { align: 'center', lineGap: 4 });
      }

      if (magnet.cta_page_url) {
        doc.moveDown(1);
        doc.fillColor(accentColor)
          .font('Helvetica-Bold')
          .fontSize(12)
          .text(magnet.cta_page_url, {
            align: 'center',
            link: magnet.cta_page_url,
            underline: true,
          });
      }
    }

    // ---- FOOTER (on every page except title) ----
    const footerText = magnet.pdf_footer_text
      || `Generated by MagnetVault for ${magnet.creators.display_name || magnet.creators.channel_name}`;

    const pageCount = doc.bufferedPageRange().count;
    for (let i = 1; i < pageCount; i++) {
      doc.switchToPage(i);
      doc.fillColor(mutedColor)
        .font('Helvetica')
        .fontSize(8)
        .text(
          footerText,
          doc.page.margins.left,
          doc.page.height - 40,
          {
            align: 'center',
            width: doc.page.width - doc.page.margins.left - doc.page.margins.right,
          }
        );
    }

    doc.end();
  });
}

function renderMarkdownToPDF(
  doc: PDFKit.PDFDocument,
  markdown: string,
  colors: { textColor: string; accentColor: string; mutedColor: string }
): void {
  const lines = markdown.split('\n');
  let inList = false;

  for (const line of lines) {
    const trimmed = line.trim();

    if (!trimmed) {
      doc.moveDown(0.5);
      inList = false;
      continue;
    }

    // Heading 1
    if (trimmed.startsWith('# ')) {
      doc.moveDown(1.5)
        .fillColor(colors.accentColor)
        .font('Helvetica-Bold')
        .fontSize(20)
        .text(trimmed.slice(2), { paragraphGap: 8 })
        .font('Helvetica')
        .fontSize(11)
        .fillColor(colors.textColor);
      continue;
    }

    // Heading 2
    if (trimmed.startsWith('## ')) {
      doc.moveDown(1)
        .fillColor(colors.textColor)
        .font('Helvetica-Bold')
        .fontSize(16)
        .text(trimmed.slice(3), { paragraphGap: 6 })
        .font('Helvetica')
        .fontSize(11);
      continue;
    }

    // Heading 3
    if (trimmed.startsWith('### ')) {
      doc.moveDown(0.8)
        .font('Helvetica-Bold')
        .fontSize(13)
        .text(trimmed.slice(4), { paragraphGap: 4 })
        .font('Helvetica')
        .fontSize(11);
      continue;
    }

    // Heading 4
    if (trimmed.startsWith('#### ')) {
      doc.moveDown(0.5)
        .font('Helvetica-Bold')
        .fontSize(11)
        .text(trimmed.slice(5), { paragraphGap: 4 })
        .font('Helvetica');
      continue;
    }

    // Horizontal rule
    if (trimmed === '---' || trimmed === '***' || trimmed === '___') {
      doc.moveDown(0.5)
        .strokeColor('#E2E8F0')
        .lineWidth(0.5)
        .moveTo(doc.page.margins.left, doc.y)
        .lineTo(doc.page.width - doc.page.margins.right, doc.y)
        .stroke()
        .moveDown(0.5);
      continue;
    }

    // Blockquote
    if (trimmed.startsWith('> ')) {
      doc.fillColor(colors.mutedColor)
        .font('Helvetica-Oblique')
        .text(trimmed.slice(2), { indent: 20, paragraphGap: 6, lineGap: 3 })
        .font('Helvetica')
        .fillColor(colors.textColor);
      continue;
    }

    // Bullet list
    if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      doc.text(`\u2022  ${trimmed.slice(2)}`, { indent: 15, paragraphGap: 4, lineGap: 2 });
      inList = true;
      continue;
    }

    // Numbered list
    const numMatch = trimmed.match(/^(\d+)\.\s+(.+)/);
    if (numMatch) {
      doc.text(`${numMatch[1]}.  ${numMatch[2]}`, { indent: 15, paragraphGap: 4, lineGap: 2 });
      inList = true;
      continue;
    }

    // Regular paragraph — strip inline markdown
    const cleanText = trimmed
      .replace(/\*\*([^*]+)\*\*/g, '$1')
      .replace(/\*([^*]+)\*/g, '$1')
      .replace(/_([^_]+)_/g, '$1');

    doc.fillColor(colors.textColor)
      .font('Helvetica')
      .fontSize(11)
      .text(cleanText, { paragraphGap: inList ? 4 : 8, lineGap: 3 });

    inList = false;
  }
}
